-- Banco de dados: financas
-- Host: mysql746.umbler.com:41890
-- Usuário: leandrofinancas
-- Senha: a36825700

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    role ENUM('admin', 'corretor') NOT NULL DEFAULT 'corretor',
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    deletado_em DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS imoveis (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT DEFAULT NULL,
    tipo ENUM('casa', 'apartamento', 'terreno', 'comercial', 'outro') NOT NULL DEFAULT 'apartamento',
    situacao ENUM('venda', 'locacao', 'venda_e_locacao') NOT NULL DEFAULT 'venda',
    status ENUM('disponivel', 'alugado', 'vendido') NOT NULL DEFAULT 'disponivel',
    valor_venda DECIMAL(14,2) DEFAULT NULL,
    valor_aluguel DECIMAL(14,2) DEFAULT NULL,
    area_m2 DECIMAL(10,2) DEFAULT NULL,
    quartos TINYINT UNSIGNED DEFAULT NULL,
    banheiros TINYINT UNSIGNED DEFAULT NULL,
    garagem TINYINT UNSIGNED DEFAULT NULL,
    endereco VARCHAR(255) DEFAULT NULL,
    cidade VARCHAR(120) DEFAULT NULL,
    bairro VARCHAR(120) DEFAULT NULL,
    cep VARCHAR(20) DEFAULT NULL,
    proprietario_id INT UNSIGNED DEFAULT NULL,
    corretor_id INT UNSIGNED DEFAULT NULL,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    deletado_em DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (proprietario_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (corretor_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS imovel_media (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    imovel_id INT UNSIGNED NOT NULL,
    tipo ENUM('imagem', 'video') NOT NULL DEFAULT 'imagem',
    url VARCHAR(255) NOT NULL,
    ordem TINYINT UNSIGNED NOT NULL DEFAULT 1,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (imovel_id) REFERENCES imoveis(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blog_posts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    resumo VARCHAR(255) DEFAULT NULL,
    conteudo TEXT NOT NULL,
    autor_id INT UNSIGNED DEFAULT NULL,
    publicado_em DATETIME DEFAULT NULL,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    deletado_em DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (autor_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS leads (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    imovel_id INT UNSIGNED DEFAULT NULL,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150) DEFAULT NULL,
    telefone VARCHAR(50) DEFAULT NULL,
    mensagem TEXT DEFAULT NULL,
    status ENUM('novo', 'em_contato', 'arquivado') NOT NULL DEFAULT 'novo',
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (imovel_id) REFERENCES imoveis(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS contratos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    imovel_id INT UNSIGNED NOT NULL,
    corretor_id INT UNSIGNED DEFAULT NULL,
    cliente_nome VARCHAR(150) NOT NULL,
    tipo ENUM('locacao', 'venda') NOT NULL,
    valor DECIMAL(14,2) NOT NULL,
    data_inicio DATE DEFAULT NULL,
    data_fim DATE DEFAULT NULL,
    situacao ENUM('ativo', 'concluido', 'cancelado') NOT NULL DEFAULT 'ativo',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (imovel_id) REFERENCES imoveis(id) ON DELETE CASCADE,
    FOREIGN KEY (corretor_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS boletos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    contrato_id INT UNSIGNED NOT NULL,
    vencimento DATE NOT NULL,
    valor DECIMAL(14,2) NOT NULL,
    status ENUM('pendente', 'pago', 'atrasado') NOT NULL DEFAULT 'pendente',
    nota VARCHAR(255) DEFAULT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (contrato_id) REFERENCES contratos(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
